export const defaultRanks: { level: number; name: string }[] = [
  { level: 1, name: "Mostly Harmless" },
  { level: 2, name: "Don't Panic" },
  { level: 3, name: "Fresh Off O Street" },
  { level: 4, name: "Vogon Poetry Victim" },
  { level: 5, name: "Runza Rookie" },
  { level: 6, name: "Towel Carrier" },
  { level: 7, name: "Haymarket Wanderer" },
  { level: 8, name: "Sub-Sub-Sub Paragraph" },
  { level: 9, name: "Cornfield NPC" },
  { level: 10, name: "Babel Fish Recipient" },
  { level: 11, name: "Valentino's Regular" },
  { level: 12, name: "Perfectly Normal Chatter" },
  { level: 13, name: "Amigos Apologist" },
  { level: 14, name: "Nutri-Matic Drinker" },
  { level: 15, name: "Sea of Red Droplet" },
  { level: 16, name: "SEP Field Generator" },
  { level: 17, name: "Sunken Gardens Tourist" },
  { level: 18, name: "Share and Enjoy" },
  { level: 19, name: "Bugeater" },
  { level: 20, name: "Infinite Improbability Passenger" },
  { level: 21, name: "Railyard Patio Sitter" },
  { level: 22, name: "Paranoid Android" },
  { level: 23, name: "Husker By Osmosis" },
  { level: 24, name: "Pan Galactic Gargle Blaster Taster" },
  { level: 25, name: "Memorial Stadium Seat Warmer" },
  { level: 26, name: "Slartibartfast Apprentice" },
  { level: 27, name: "I-80 Survivor" },
  { level: 28, name: "Zaphod's Spare Head" },
  { level: 29, name: "Tornado Watcher" },
  { level: 30, name: "Heart of Gold Stowaway" },
  { level: 31, name: "Runza Connoisseur" },
  { level: 32, name: "Bistromathician" },
  { level: 33, name: "Herbie Husker's Stunt Double" },
  { level: 34, name: "Eccentrica Gallumbits Fan" },
  { level: 35, name: "Detasseling Veteran" },
  { level: 36, name: "Ravenous Bugblatter Survivor" },
  { level: 37, name: "Pinnacle Bank Arena VIP" },
  { level: 38, name: "Magrathean Intern" },
  { level: 39, name: "Lil' Red Truther" },
  { level: 40, name: "Deep Thought Consultant" },
  { level: 41, name: "Corn Palace Pilgrim" },
  { level: 42, name: "The Answer" },
  { level: 43, name: "Chimney Rock Photographer" },
  { level: 44, name: "Total Perspective Vortex Survivor" },
  { level: 45, name: "Ivanna Cone Addict" },
  { level: 46, name: "Ford Prefect's Drinking Buddy" },
  { level: 47, name: "Nebraska Nice Certified" },
  { level: 48, name: "Krikkit Warrior" },
  { level: 49, name: "Saltdogs Season Ticket Holder" },
  { level: 50, name: "Zarniwoop's Secretary" },
  { level: 51, name: "Husker Power Lifter" },
  { level: 52, name: "Hotblack Desiato's Roadie" },
  { level: 53, name: "Arbor Day Founder" },
  { level: 54, name: "Prostetnic Vogon Lieutenant" },
  { level: 55, name: "Scott Frost Apologist" },
  { level: 56, name: "Gag Halfrunt's Patient" },
  { level: 57, name: "Goodlife District Regular" },
  { level: 58, name: "Dish of the Day Orderer" },
  { level: 59, name: "Tom Osborne Disciple" },
  { level: 60, name: "Ruler of the Universe" },
  { level: 61, name: "Children's Zoo Enjoyer" },
  { level: 62, name: "Joo Janta 200 Super-Chromatic Wearer" },
  { level: 63, name: "County Fair Corn Dog Scholar" },
  { level: 64, name: "Dentarthurdent" },
  { level: 65, name: "Misty's Regular" },
  { level: 66, name: "Brockian Ultra-Cricket Captain" },
  { level: 67, name: "Helicopter Parent of the Corn" },
  { level: 68, name: "Fenchurch's Co-Pilot" },
  { level: 69, name: "Nice (and also Barry's alum)" },
  { level: 70, name: "Disaster Area Front Row" },
  { level: 71, name: "Memorial Stadium Balloon Releaser" },
  { level: 72, name: "Guide Mark II Handler" },
  { level: 73, name: "Nebraska Legislature Unicameralist" },
  { level: 74, name: "Agrajag's Nemesis" },
  { level: 75, name: "Tunnel Walk Legend" },
  { level: 76, name: "Hactar Fragment" },
  { level: 77, name: "Kool-Aid Point Drinker" },
  { level: 78, name: "Wonko the Sane" },
  { level: 79, name: "Sandhills Cryptid" },
  { level: 80, name: "Trillian-Level Intellect" },
  { level: 81, name: "Runza Franchise Owner" },
  { level: 82, name: "Starship Bistromath Captain" },
  { level: 83, name: "Platte River Wide and Shallow" },
  { level: 84, name: "Prak (Knows All Truth)" },
  { level: 85, name: "Fifth-Year Senior at UNL" },
  { level: 86, name: "Magrathean Planet Designer" },
  { level: 87, name: "Henry Doorly Zoo Docent" },
  { level: 88, name: "Zaphodista Revolutionary" },
  { level: 89, name: "Applejack's Bartender" },
  { level: 90, name: "Deep Thought Successor" },
  { level: 91, name: "Big Red Royalty" },
  { level: 92, name: "Megadodo Publications Editor" },
  { level: 93, name: "Nebraska Wind Whisperer" },
  { level: 94, name: "Lord High President of the Galaxy" },
  { level: 95, name: "Cornhusker Emeritus" },
  { level: 96, name: "So Long and Thanks for All the Fish" },
  { level: 97, name: "GBR Incarnate" },
  { level: 98, name: "Heart of Gold Commander" },
  { level: 99, name: "Third Largest City Permanent Resident" },
  { level: 100, name: "Keeper of the Towel and the Corn" },
];
